### ISSUE TITLE
Pushing 0.0.2-SNAPSHOT to maven central

### ISSUE THREAD

**Issue by akmorrow13** [fnothaft/jsr203-s3a#2]
Can we cut a release of the 0.0.2-SNAPSHOT? Or do I have permissions to do so?

**Comment by akmorrow13** [comment]
bump @fnothaft

**Comment by fnothaft** [comment]
Thanks for the ping, missed your original message. I'll cut a release today or tomorrow.

**Comment by akmorrow13** [comment]
Hi @fnothaft has this been released?

**Comment by fnothaft** [comment]
Release has been made, should show up in Maven Central later today.

**Comment by akmorrow13** [comment]
Thanks @fnothaft!
